from: 
https://medium.com/geekculture/cross-validation-techniques-33d389897878#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjYzMWZhZTliNTk0MGEyZDFmYmZmYjAwNDAzZDRjZjgwYTIxYmUwNGUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2NTgwNDU5NzAsImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwOTU3MDEwNzcxNTgyNzc0MTAzMiIsImVtYWlsIjoiZWxhaGVkb3JhbmlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsIm5hbWUiOiJlbGFoZSBkb3JhbmkiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUl0YnZta0NQZVhNVlRXT1BqM2sxVUd5QkZvVTRoTUhCWnBUR3ExUzh5dWE9czk2LWMiLCJnaXZlbl9uYW1lIjoiZWxhaGUiLCJmYW1pbHlfbmFtZSI6ImRvcmFuaSIsImlhdCI6MTY1ODA0NjI3MCwiZXhwIjoxNjU4MDQ5ODcwLCJqdGkiOiI2NmI0ZTZlNDQ1MWRkZGVlOTU1MDA4NTI5OTQ4ZWY1MmNjMDA5MjM1In0.jnkkrJ82iOogdufns1fY-1FsheDtYd7nVv_WlCn6FbcUBns2z80Pm4yi263PsY9P6poVVcYVTxXuy5wiC43KuZwRxM5iFchI7yIIZCXt7WFaGGw72K40lRtgANZ7lICuu3LxUWO2GLPltH1n06soGr2CAgxWFA33XMmRuGh8DqLD25nT4WwHQS7G2lweXkw35pFR_rqNGtRruLDmWIN5QLoQ0PkrNUvCb0ps5IamP26alYphn5LOlIjjcoRHZbElwSZxKT7NBh3bmamTrnJ0yUh0APDeeDN89pERTMS_QjJ2OBGbcmbK01ghX95W-P5eNRLBQGGscu3wuD5qtSK7-w

→ Introduction
→ What is Cross-Validation?
→ Different Types of Cross-Validation
1. Hold-Out Method
2. K-Folds Method
3. Repeated K-Folds Method
4. Stratified K-Folds Method
5. Group K-Folds Method
6. Shuffle Split Method
7. Stratified Shuffle Split Method
8. Group Shuffle Split Method
9. Leave-One-Out Method
10. Leave-P-Out Method
11. Leave-One-Group-Out Method
12. Leave-P-Group-Out Method
13. Time Series Cross-Validation Method
14. Blocked Cross-Validation Method
15. Nested Cross-Validation Method
→ Conclusion
→ Reference

# Define dataset

In [28]:
import numpy as np 
import pandas as pd 

data = ['Subset1', 'Subset2', 'Subset3', 'Subset4', 'Subset5', 'Subset6', 'Subset7', 'Subset8', 'Subset9', 'Subset10']
Y = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]
df = {"data":data, "Y":Y}
df = pd.DataFrame(df)
df

data  Y
0   Subset1  1
1   Subset2  0
2   Subset3  1
3   Subset4  0
4   Subset5  0
5   Subset6  1
6   Subset7  1
7   Subset8  0
8   Subset9  1
9  Subset10  0

# Hold-Out Method

In [2]:
from sklearn import model_selection

x_train, x_test, y_train, y_test = model_selection.train_test_split(df.data, df.Y, test_size = 0.2)
for i,n in zip(x_train, y_train):
  print(i, "::", n)
for i, n in zip(x_test, y_test):
  print(i, "::", n)

Subset7 :: 1
Subset2 :: 0
Subset8 :: 0
Subset5 :: 0
Subset4 :: 0
Subset1 :: 1
Subset3 :: 1
Subset6 :: 1
Subset9 :: 1
Subset10 :: 0


In [3]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(df.data, df.Y, test_size = 0.2, stratify = df.Y)
for i,n in zip(x_train, y_train):
  print(i, "::", n)
for i, n in zip(x_test, y_test):
  print(i, "::", n)

Subset5 :: 0
Subset2 :: 0
Subset8 :: 0
Subset4 :: 0
Subset3 :: 1
Subset1 :: 1
Subset9 :: 1
Subset7 :: 1
Subset10 :: 0
Subset6 :: 1


# K-fold Model Selection

In [8]:
kfold = model_selection.KFold(n_splits=5)

print("Train", "||", "Test")
for train, test in kfold.split(df.data, df.Y):
  print(train, "||", test)

Train || Test
[2 3 4 5 6 7 8 9] || [0 1]
[0 1 4 5 6 7 8 9] || [2 3]
[0 1 2 3 6 7 8 9] || [4 5]
[0 1 2 3 4 5 8 9] || [6 7]
[0 1 2 3 4 5 6 7] || [8 9]


In [9]:
tn = []
tt = []
for train, test in kfold.split(data):
  tn.append(np.take(data,train))
  tt.append(np.take(data,test))
kfold_df = pd.DataFrame({"train":tn, "test":tt})
kfold_df

train                 test
0  [Subset3, Subset4, Subset5, Subset6, Subset7, ...   [Subset1, Subset2]
1  [Subset1, Subset2, Subset5, Subset6, Subset7, ...   [Subset3, Subset4]
2  [Subset1, Subset2, Subset3, Subset4, Subset7, ...   [Subset5, Subset6]
3  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset7, Subset8]
4  [Subset1, Subset2, Subset3, Subset4, Subset5, ...  [Subset9, Subset10]

In [14]:
kfold = model_selection.KFold(n_splits=5, shuffle=True, random_state=10)
print("Train", "||", "Test")
for train, test in kfold.split(data):
  print(train, "||", test)

Train || Test
[0 1 3 4 5 6 7 9] || [2 8]
[0 1 2 3 4 7 8 9] || [5 6]
[0 2 4 5 6 7 8 9] || [1 3]
[1 2 3 4 5 6 8 9] || [0 7]
[0 1 2 3 5 6 7 8] || [4 9]


In [15]:
tn = []
tt = []
for train, test in kfold.split(data):
  tn.append(np.take(data,train))
  tt.append(np.take(data,test))
kfold_df = pd.DataFrame({"train":tn, "test":tt})
kfold_df

train                 test
0  [Subset1, Subset2, Subset4, Subset5, Subset6, ...   [Subset3, Subset9]
1  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset6, Subset7]
2  [Subset1, Subset3, Subset5, Subset6, Subset7, ...   [Subset2, Subset4]
3  [Subset2, Subset3, Subset4, Subset5, Subset6, ...   [Subset1, Subset8]
4  [Subset1, Subset2, Subset3, Subset4, Subset6, ...  [Subset5, Subset10]

# Repeated K-folds Method

In [16]:
Rkfold = model_selection.RepeatedKFold(n_splits=5, n_repeats=5, random_state=2)
print("Train", "||", "Test")
for train, test in Rkfold.split(data):
  print(train, "||", test)

Train || Test
[0 2 3 5 6 7 8 9] || [1 4]
[1 2 3 4 6 7 8 9] || [0 5]
[0 1 3 4 5 6 8 9] || [2 7]
[0 1 2 4 5 7 8 9] || [3 6]
[0 1 2 3 4 5 6 7] || [8 9]
[0 2 3 4 5 7 8 9] || [1 6]
[1 3 4 5 6 7 8 9] || [0 2]
[0 1 2 4 5 6 7 8] || [3 9]
[0 1 2 3 4 5 6 9] || [7 8]
[0 1 2 3 6 7 8 9] || [4 5]
[0 1 2 3 5 6 7 8] || [4 9]
[1 2 3 4 6 7 8 9] || [0 5]
[0 2 3 4 5 6 7 9] || [1 8]
[0 1 3 4 5 7 8 9] || [2 6]
[0 1 2 4 5 6 8 9] || [3 7]
[0 1 2 3 4 6 7 8] || [5 9]
[1 2 3 4 5 6 7 9] || [0 8]
[0 3 4 5 6 7 8 9] || [1 2]
[0 1 2 4 5 6 8 9] || [3 7]
[0 1 2 3 5 7 8 9] || [4 6]
[0 1 2 4 6 7 8 9] || [3 5]
[0 1 2 3 4 5 7 9] || [6 8]
[1 2 3 4 5 6 8 9] || [0 7]
[0 2 3 4 5 6 7 8] || [1 9]
[0 1 3 5 6 7 8 9] || [2 4]


In [17]:
tn = []
tt = []
for train, test in Rkfold.split(data):
  tn.append(np.take(data,train))
  tt.append(np.take(data,test))
Rkfold_df = pd.DataFrame({"train":tn, "test":tt})
Rkfold_df

train                 test
0   [Subset1, Subset3, Subset4, Subset6, Subset7, ...   [Subset2, Subset5]
1   [Subset2, Subset3, Subset4, Subset5, Subset7, ...   [Subset1, Subset6]
2   [Subset1, Subset2, Subset4, Subset5, Subset6, ...   [Subset3, Subset8]
3   [Subset1, Subset2, Subset3, Subset5, Subset6, ...   [Subset4, Subset7]
4   [Subset1, Subset2, Subset3, Subset4, Subset5, ...  [Subset9, Subset10]
5   [Subset1, Subset3, Subset4, Subset5, Subset6, ...   [Subset2, Subset7]
6   [Subset2, Subset4, Subset5, Subset6, Subset7, ...   [Subset1, Subset3]
7   [Subset1, Subset2, Subset3, Subset5, Subset6, ...  [Subset4, Subset10]
8   [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset8, Subset9]
9   [Subset1, Subset2, Subset3, Subset4, Subset7, ...   [Subset5, Subset6]
10  [Subset1, Subset2, Subset3, Subset4, Subset6, ...  [Subset5, Subset10]
11  [Subset2, Subset3, Subset4, Subset5, Subset7, ...   [Subset1, Subset6]
12  [Subset1, Subset3, Subset4, Subset5, Subset6, ...   [Subset2, Subset9]
13  [Subset1, Subset2, Subset4, Subset5, Subset6, ...   [Subset3, Subset7]
14  [Subset1, Subset2, Subset3, Subset5, Subset6, ...   [Subset4, Subset8]
15  [Subset1, Subset2, Subset3, Subset4, Subset5, ...  [Subset6, Subset10]
16  [Subset2, Subset3, Subset4, Subset5, Subset6, ...   [Subset1, Subset9]
17  [Subset1, Subset4, Subset5, Subset6, Subset7, ...   [Subset2, Subset3]
18  [Subset1, Subset2, Subset3, Subset5, Subset6, ...   [Subset4, Subset8]
19  [Subset1, Subset2, Subset3, Subset4, Subset6, ...   [Subset5, Subset7]
20  [Subset1, Subset2, Subset3, Subset5, Subset7, ...   [Subset4, Subset6]
21  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset7, Subset9]
22  [Subset2, Subset3, Subset4, Subset5, Subset6, ...   [Subset1, Subset8]
23  [Subset1, Subset3, Subset4, Subset5, Subset6, ...  [Subset2, Subset10]
24  [Subset1, Subset2, Subset4, Subset6, Subset7, ...   [Subset3, Subset5]

# Stratified K-Fold Method:

In [21]:
strkfold = model_selection.StratifiedKFold(n_splits=5, shuffle = True, random_state =10)
tn_x = []
tn_y = []
tt_x = []
tt_y = []
for train, test in strkfold.split(data, Y):
  tn_x.append(np.take(data,train))
  tn_y.append(np.take(Y,train))
  tt_x.append(np.take(data,test))
  tt_y.append(np.take(Y,test))
strkfold_train = pd.DataFrame({"train_x":tn_x, "train_y":tn_y})
strkfold_test = pd.DataFrame({'test_x':tt_x, "test_y":tt_y})

In [19]:
strkfold_train

train_x                   train_y
0  [Subset3, Subset4, Subset5, Subset6, Subset7, ...  [1, 0, 0, 1, 1, 0, 1, 0]
1  [Subset1, Subset2, Subset5, Subset6, Subset7, ...  [1, 0, 0, 1, 1, 0, 1, 0]
2  [Subset1, Subset2, Subset3, Subset4, Subset7, ...  [1, 0, 1, 0, 1, 0, 1, 0]
3  [Subset1, Subset2, Subset3, Subset4, Subset5, ...  [1, 0, 1, 0, 0, 1, 1, 0]
4  [Subset1, Subset2, Subset3, Subset4, Subset5, ...  [1, 0, 1, 0, 0, 1, 1, 0]

In [20]:
strkfold_test

test_x  test_y
0   [Subset1, Subset2]  [1, 0]
1   [Subset3, Subset4]  [1, 0]
2   [Subset5, Subset6]  [0, 1]
3   [Subset7, Subset8]  [1, 0]
4  [Subset9, Subset10]  [1, 0]

# Group K-Folds Method:

In [50]:
from tokenize import group


grpkfold = model_selection.GroupKFold(n_splits=2)
print("Train", "||", "Test")

groups = (1, 2, 3, 1, 2, 3, 3, 3, 2, 1)
for train, test in grpkfold.split(data, Y, groups=groups):
  print(train, "||", test)

Train || Test
[0 1 3 4 8 9] || [2 5 6 7]
[2 5 6 7] || [0 1 3 4 8 9]


In [51]:
tn = []
tt = []
for train, test in grpkfold.split(data, Y, groups=groups):
  tn.append(np.take(data,train))
  tt.append(np.take(data,test))
grpkfold_df = pd.DataFrame({"train":tn, "test":tt})
grpkfold_df

train  \
0  [Subset1, Subset2, Subset4, Subset5, Subset9, ...   
1               [Subset3, Subset6, Subset7, Subset8]   

                                                test  
0               [Subset3, Subset6, Subset7, Subset8]  
1  [Subset1, Subset2, Subset4, Subset5, Subset9, ...

In [52]:
# Example of scikit-learn
import numpy as np
from sklearn.model_selection import GroupShuffleSplit
X = np.ones(shape=(8, 2))
y = np.ones(shape=(8, 1))
groups = np.array([1, 1, 2, 2, 2, 3, 3, 3])
print(groups.shape)

gss = GroupShuffleSplit(n_splits=2, train_size=.7, random_state=42)
gss.get_n_splits()

for train_idx, test_idx in gss.split(X, y, groups):
    print("TRAIN:", train_idx, "TEST:", test_idx)

(8,)
TRAIN: [2 3 4 5 6 7] TEST: [0 1]
TRAIN: [0 1 5 6 7] TEST: [2 3 4]


# Shuffle Split Method:

Not suitable for an imbalanced dataset.

In [92]:
shsplit = model_selection.ShuffleSplit(n_splits=5, random_state=10)
print("Train", "||", "Test")
for train, test in shsplit.split(data):
  print(train, "||", test)

Train || Test
[2 5 6 3 1 0 7 4 9] || [8]
[3 4 7 6 8 9 2 1 0] || [5]
[6 2 5 7 8 9 0 3 4] || [1]
[7 5 2 3 9 6 4 8 1] || [0]
[0 9 5 4 1 7 8 6 3] || [2]


In [54]:
tn = []
tt = []
for train, test in shsplit.split(data):
  tn.append(np.take(data,train))
  tt.append(np.take(data,test))
shsplit_df = pd.DataFrame({"train":tn, "test":tt})
shsplit_df

train                 test
0  [Subset2, Subset3, Subset10, Subset7, Subset8,...   [Subset6, Subset5]
1  [Subset3, Subset2, Subset10, Subset5, Subset1,...   [Subset4, Subset9]
2  [Subset9, Subset4, Subset10, Subset5, Subset8,...   [Subset1, Subset6]
3  [Subset8, Subset7, Subset4, Subset1, Subset3, ...  [Subset5, Subset10]
4  [Subset3, Subset9, Subset7, Subset10, Subset5,...   [Subset8, Subset4]

# Stratified Shuffle Split Method:

In [60]:
strshsplit = model_selection.StratifiedShuffleSplit(n_splits=5, test_size=0.2)
print("Train", "||", "Test")
for train, test in strshsplit.split(data, Y):
  print(train, "||", test)

Train || Test
[0 8 2 9 1 6 4 7] || [5 3]
[9 3 8 4 2 6 7 5] || [1 0]
[5 1 7 4 6 3 8 0] || [9 2]
[7 6 5 2 1 4 9 8] || [0 3]
[7 9 3 0 5 4 2 6] || [1 8]


In [56]:
tn_x = []
tn_y = []
tt_x = []
tt_y = []
for train, test in strshsplit.split(data, Y):
  tn_x.append(np.take(data,train))
  tn_y.append(np.take(Y,train))
  tt_x.append(np.take(data,test))
  tt_y.append(np.take(Y,test))
strshsplit_train = pd.DataFrame({"train_x":tn_x, "train_y":tn_y})
strshsplit_test = pd.DataFrame({'test_x':tt_x, "test_y":tt_y})

# Group Shuffle Split Method:

In [79]:
grpshsplit = model_selection.GroupShuffleSplit(n_splits=5, random_state=10)
print("Train", "||", "Test")
groups = (1, 2, 1, 1, 2, 2, 2, 1, 1, 1)
for train, test in grpshsplit.split(data, groups=groups):
  print(train, "||", test)

Train || Test
[1 4 5 6] || [0 2 3 7 8 9]
[1 4 5 6] || [0 2 3 7 8 9]
[0 2 3 7 8 9] || [1 4 5 6]
[1 4 5 6] || [0 2 3 7 8 9]
[0 2 3 7 8 9] || [1 4 5 6]


In [93]:
tn = []
tt = []
for train, test in grpshsplit.split(data, groups=groups):
  tn.append(np.take(data,train))
  tt.append(np.take(data,test))
grpshsplit_df = pd.DataFrame({"train":tn, "test":tt})
grpshsplit_df

train  \
0               [Subset2, Subset5, Subset6, Subset7]   
1               [Subset2, Subset5, Subset6, Subset7]   
2  [Subset1, Subset3, Subset4, Subset8, Subset9, ...   
3               [Subset2, Subset5, Subset6, Subset7]   
4  [Subset1, Subset3, Subset4, Subset8, Subset9, ...   

                                                test  
0  [Subset1, Subset3, Subset4, Subset8, Subset9, ...  
1  [Subset1, Subset3, Subset4, Subset8, Subset9, ...  
2               [Subset2, Subset5, Subset6, Subset7]  
3  [Subset1, Subset3, Subset4, Subset8, Subset9, ...  
4               [Subset2, Subset5, Subset6, Subset7]

#  Leave-One-Out Method:

In [94]:
loo = model_selection.LeaveOneOut()
print("Train", "||", "Test")
for train, test in loo.split(data):
  print(train, "||", test)

Train || Test
[1 2 3 4 5 6 7 8 9] || [0]
[0 2 3 4 5 6 7 8 9] || [1]
[0 1 3 4 5 6 7 8 9] || [2]
[0 1 2 4 5 6 7 8 9] || [3]
[0 1 2 3 5 6 7 8 9] || [4]
[0 1 2 3 4 6 7 8 9] || [5]
[0 1 2 3 4 5 7 8 9] || [6]
[0 1 2 3 4 5 6 8 9] || [7]
[0 1 2 3 4 5 6 7 9] || [8]
[0 1 2 3 4 5 6 7 8] || [9]


In [95]:
tn = []
tt = []
for train, test in loo.split(data):
  tn.append(np.take(data,train))
  tt.append(np.take(data,test))
loo_df = pd.DataFrame({"train":tn, "test":tt})
loo_df

train        test
0  [Subset2, Subset3, Subset4, Subset5, Subset6, ...   [Subset1]
1  [Subset1, Subset3, Subset4, Subset5, Subset6, ...   [Subset2]
2  [Subset1, Subset2, Subset4, Subset5, Subset6, ...   [Subset3]
3  [Subset1, Subset2, Subset3, Subset5, Subset6, ...   [Subset4]
4  [Subset1, Subset2, Subset3, Subset4, Subset6, ...   [Subset5]
5  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset6]
6  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset7]
7  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset8]
8  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset9]
9  [Subset1, Subset2, Subset3, Subset4, Subset5, ...  [Subset10]

# Leave-P-Out Method:

In [96]:
lpo = model_selection.LeavePOut(2)
tn = []
tt = []
for train, test in lpo.split(data):
  tn.append(np.take(data,train))
  tt.append(np.take(data,test))
lpo_df = pd.DataFrame({"train":tn, "test":tt})
lpo_df

train                 test
0   [Subset3, Subset4, Subset5, Subset6, Subset7, ...   [Subset1, Subset2]
1   [Subset2, Subset4, Subset5, Subset6, Subset7, ...   [Subset1, Subset3]
2   [Subset2, Subset3, Subset5, Subset6, Subset7, ...   [Subset1, Subset4]
3   [Subset2, Subset3, Subset4, Subset6, Subset7, ...   [Subset1, Subset5]
4   [Subset2, Subset3, Subset4, Subset5, Subset7, ...   [Subset1, Subset6]
5   [Subset2, Subset3, Subset4, Subset5, Subset6, ...   [Subset1, Subset7]
6   [Subset2, Subset3, Subset4, Subset5, Subset6, ...   [Subset1, Subset8]
7   [Subset2, Subset3, Subset4, Subset5, Subset6, ...   [Subset1, Subset9]
8   [Subset2, Subset3, Subset4, Subset5, Subset6, ...  [Subset1, Subset10]
9   [Subset1, Subset4, Subset5, Subset6, Subset7, ...   [Subset2, Subset3]
10  [Subset1, Subset3, Subset5, Subset6, Subset7, ...   [Subset2, Subset4]
11  [Subset1, Subset3, Subset4, Subset6, Subset7, ...   [Subset2, Subset5]
12  [Subset1, Subset3, Subset4, Subset5, Subset7, ...   [Subset2, Subset6]
13  [Subset1, Subset3, Subset4, Subset5, Subset6, ...   [Subset2, Subset7]
14  [Subset1, Subset3, Subset4, Subset5, Subset6, ...   [Subset2, Subset8]
15  [Subset1, Subset3, Subset4, Subset5, Subset6, ...   [Subset2, Subset9]
16  [Subset1, Subset3, Subset4, Subset5, Subset6, ...  [Subset2, Subset10]
17  [Subset1, Subset2, Subset5, Subset6, Subset7, ...   [Subset3, Subset4]
18  [Subset1, Subset2, Subset4, Subset6, Subset7, ...   [Subset3, Subset5]
19  [Subset1, Subset2, Subset4, Subset5, Subset7, ...   [Subset3, Subset6]
20  [Subset1, Subset2, Subset4, Subset5, Subset6, ...   [Subset3, Subset7]
21  [Subset1, Subset2, Subset4, Subset5, Subset6, ...   [Subset3, Subset8]
22  [Subset1, Subset2, Subset4, Subset5, Subset6, ...   [Subset3, Subset9]
23  [Subset1, Subset2, Subset4, Subset5, Subset6, ...  [Subset3, Subset10]
24  [Subset1, Subset2, Subset3, Subset6, Subset7, ...   [Subset4, Subset5]
25  [Subset1, Subset2, Subset3, Subset5, Subset7, ...   [Subset4, Subset6]
26  [Subset1, Subset2, Subset3, Subset5, Subset6, ...   [Subset4, Subset7]
27  [Subset1, Subset2, Subset3, Subset5, Subset6, ...   [Subset4, Subset8]
28  [Subset1, Subset2, Subset3, Subset5, Subset6, ...   [Subset4, Subset9]
29  [Subset1, Subset2, Subset3, Subset5, Subset6, ...  [Subset4, Subset10]
30  [Subset1, Subset2, Subset3, Subset4, Subset7, ...   [Subset5, Subset6]
31  [Subset1, Subset2, Subset3, Subset4, Subset6, ...   [Subset5, Subset7]
32  [Subset1, Subset2, Subset3, Subset4, Subset6, ...   [Subset5, Subset8]
33  [Subset1, Subset2, Subset3, Subset4, Subset6, ...   [Subset5, Subset9]
34  [Subset1, Subset2, Subset3, Subset4, Subset6, ...  [Subset5, Subset10]
35  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset6, Subset7]
36  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset6, Subset8]
37  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset6, Subset9]
38  [Subset1, Subset2, Subset3, Subset4, Subset5, ...  [Subset6, Subset10]
39  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset7, Subset8]
40  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset7, Subset9]
41  [Subset1, Subset2, Subset3, Subset4, Subset5, ...  [Subset7, Subset10]
42  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset8, Subset9]
43  [Subset1, Subset2, Subset3, Subset4, Subset5, ...  [Subset8, Subset10]
44  [Subset1, Subset2, Subset3, Subset4, Subset5, ...  [Subset9, Subset10]

In [97]:
tsplit = model_selection.TimeSeriesSplit(n_splits=9, max_train_size=10)
print("Train", "||", "Test")
for train, test in tsplit.split(data):
  print(train, "||", test)

Train || Test
[0] || [1]
[0 1] || [2]
[0 1 2] || [3]
[0 1 2 3] || [4]
[0 1 2 3 4] || [5]
[0 1 2 3 4 5] || [6]
[0 1 2 3 4 5 6] || [7]
[0 1 2 3 4 5 6 7] || [8]
[0 1 2 3 4 5 6 7 8] || [9]


In [98]:
tn = []
tt = []
for train, test in tsplit.split(data):
  tn.append(np.take(data,train))
  tt.append(np.take(data,test))
tsplit_df = pd.DataFrame({"train":tn, "test":tt})
tsplit_df

train        test
0                                          [Subset1]   [Subset2]
1                                 [Subset1, Subset2]   [Subset3]
2                        [Subset1, Subset2, Subset3]   [Subset4]
3               [Subset1, Subset2, Subset3, Subset4]   [Subset5]
4      [Subset1, Subset2, Subset3, Subset4, Subset5]   [Subset6]
5  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset7]
6  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset8]
7  [Subset1, Subset2, Subset3, Subset4, Subset5, ...   [Subset9]
8  [Subset1, Subset2, Subset3, Subset4, Subset5, ...  [Subset10]

# Blocked Cross-Validation

In [100]:
blocks = 2
n = len(data) // 2

for i in [data[i:i + n] for i in range(0, len(data), n)]:
  train, test = model_selection.train_test_split(i)
  print(train, "||", test)

['Subset3', 'Subset4', 'Subset5'] || ['Subset1', 'Subset2']
['Subset6', 'Subset7', 'Subset8'] || ['Subset9', 'Subset10']


# Nested cross-validation

In [101]:
outter_cv = model_selection.KFold(n_splits=5)
inner_cv = model_selection.KFold(n_splits=4)

for train, test in outter_cv.split(data):
  tr = np.take(data, train)
  te = np.take(data, test)
  print(tr, "||", te)
  print("-----------------------------------")
  for in_train, in_test in inner_cv.split(tr):
    in_tr = np.take(tr, in_train)
    in_te = np.take(tr, in_test)
    print(in_tr, "||", in_te)
  print("<<<<<<<<<<----------------------------------->>>>>>>>>>>")

['Subset3' 'Subset4' 'Subset5' 'Subset6' 'Subset7' 'Subset8' 'Subset9'
 'Subset10'] || ['Subset1' 'Subset2']
-----------------------------------
['Subset5' 'Subset6' 'Subset7' 'Subset8' 'Subset9' 'Subset10'] || ['Subset3' 'Subset4']
['Subset3' 'Subset4' 'Subset7' 'Subset8' 'Subset9' 'Subset10'] || ['Subset5' 'Subset6']
['Subset3' 'Subset4' 'Subset5' 'Subset6' 'Subset9' 'Subset10'] || ['Subset7' 'Subset8']
['Subset3' 'Subset4' 'Subset5' 'Subset6' 'Subset7' 'Subset8'] || ['Subset9' 'Subset10']
<<<<<<<<<<----------------------------------->>>>>>>>>>>
['Subset1' 'Subset2' 'Subset5' 'Subset6' 'Subset7' 'Subset8' 'Subset9'
 'Subset10'] || ['Subset3' 'Subset4']
-----------------------------------
['Subset5' 'Subset6' 'Subset7' 'Subset8' 'Subset9' 'Subset10'] || ['Subset1' 'Subset2']
['Subset1' 'Subset2' 'Subset7' 'Subset8' 'Subset9' 'Subset10'] || ['Subset5' 'Subset6']
['Subset1' 'Subset2' 'Subset5' 'Subset6' 'Subset9' 'Subset10'] || ['Subset7' 'Subset8']
['Subset1' 'Subset2' 'Subset5' 'Subse